name: check_conduit
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=2.18.2 <3.0.0'


dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  conduit: ^4.1.5
  jaguar_jwt: ^3.0.0
